spring:
  cloud:
    config:
      name: configcenter
      server:
        git:
          uri: git@github.com:pkaq/springcloud7.git
          search-paths: cloud-config-repo
          clone-on-start: true
server:
  port: 8888