spring:
  cloud:
    config:
      server:
        overrides:
          foo: bar
  mvc:
    date-format: yyyy-MM-dd
    view:
       prefix: /web/
       suffix: .jsp
server:
  context-path: /
  port: 8090
tiger: Roar