---
spring:
  profiles: reka-alpha
  application:
    name: reka-alpha
eureka:
  instance:
    #配置主机名
    hostname: eureka.alpha
  client:
    #  、在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，
    #    所以我们需要禁用它的客户端注册行为。
    #    因为当注册中心将自己作为客户端注册的时候，发现在server上的端口被自己占据了，然后就挂了
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka.bravo:9872/eureka, http://eureka.charlie:9873/eureka
server:
  port: 9871
---
spring:
  profiles: reka-bravo
  application:
    name: reka-bravo
eureka:
  instance:
    hostname: eureka.bravo
  client:
     register-with-eureka: false
     fetch-registry: false
     service-url:
       defaultZone: http://eureka.alpha:9871/eureka, http://eureka.charlie:9873/eureka
server:
  port: 9872
---
spring:
  profiles: reka-charlie
  application:
    name: reka-charlie
eureka:
  instance:
    hostname: eureka.charlie
  client:
     register-with-eureka: false
     fetch-registry: false
     service-url:
       defaultZone: http://eureka.alpha:9871/eureka, http://eureka.bravo:9872/eureka
server:
  port: 9873
